<?php

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function meetup_node_view(&$build, $entity, $display, $view_mode) {
    $content_type = $entity->bundle();
    if ($content_type === 'event') {

      $build['meetup_addition_container'] = array(
        '#type' => 'container',
        '#prefix' => '<div class="addition-text-container">',
        '#suffix' => '</div>'
      );

      $userEventData = _checkUserEventData($entity->id());
      //ksm($userEventData);
      if($userEventData['interested'] === 1) {
          //Update Button
          $title = 'I am not interested';
          $url = Drupal\Core\Url::fromRoute('meetup.update_interested', array('event_id' => $entity->id()));

      } elseif($userEventData === -1) {
          $title = 'I am interested';
          $url = Drupal\Core\Url::fromRoute('meetup.interested', array('event_id' => $entity->id()));
      } else {
        $title = 'I am interested';
        $url = Drupal\Core\Url::fromRoute('meetup.update_interested', array('event_id' => $entity->id()));
      }

      $build['meetup_addition_container']['interested_in_event'] = [
        '#type' => 'link',
        '#title' => $title,
        '#url' => $url,
          '#attributes' => array(
              'style' => array('padding: 5px;'),
              'class' => array('btn', 'btn-primary'),
              'role' => array('button'),
          ),
      ];

      $build['meetup_addition_container']['participating_in_event'] = [
        '#type' => 'link',
        '#title' => t('I will participate'),
        '#url' => Drupal\Core\Url::fromRoute('meetup.participate', array('event_id' => $entity->id())),
        '#attributes' => array(
            'style' => array('padding: 5px;'),
            'class' => array('btn', 'btn-primary'),
            'role' => array('button'),
        ),

      ];
    }
}

function _checkUserEventData($nid) {
        $uid = \Drupal::currentUser()->id();
        //Drupal database connection
        $connection = \Drupal::database();
        //check if current user exists in database table
        $query = $connection->query("SELECT interested, participate FROM xnavi_meetup WHERE uid = :uid  AND nid = :nid;", array(':uid' => $uid, ':nid' => $nid));
        $result = $query->fetchAll();
        $userEventData = [];
        if(!empty($result)) {
            if($result[0]->interested === 'yes') {
                $userEventData['interested'] = 1;
            } else {
                $userEventData['interested'] = 0;
            };
            if($result[0]->participate === 'yes') {
                $userEventData['participate'] = 1;
            } else {
                $userEventData['participate'] = 0;
            };
            return $userEventData;
        }
        return -1;
}